sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 727633723zxc*
#  alioss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
#    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
#    bucket-name: sky-take-out
  redis:
    host: localhost
    port: 6379
    database: 9
  wechat:
    appid: wxf8bc7ebcd670699b
    secret: 30decb98aa1d0ca331e09bd32d645cb1
  shop:
    address: 广东省深圳市深圳大学沧海校区
  baidu:
    ak: AJ0dBrHzQs754GyJBwvW5wPLeaHbey6h